### ISSUE TITLE
Zusammenhänge Studiengang

### ISSUE THREAD

**Issue by DayaLuna** [marinaschlueter/Gruppenarbeit-Aufgabe-1#1]
Beim Alter habe ich floor angewendet, so haben wir nur ganze Zahlen bei dieser Spalte.
Bei den Spalten 4-6 habe ich in der neusten Version Zusammenhänge mit dem Studiengang eingefügt.
Passt das so und wollen wir jetzt die csv-Datei im Haupt-Repository hochladen?

**Comment by marinaschlueter** [comment]
Ich habe mir das jetzt mal angeguckt und finde deine Änderungen gut. Meinetwegen können wir die csv-Datei jetzt hochladen.

**Comment by DayaLuna** [comment]
Perfekt, dann kannst du das gerne machen.
